/**
 * The consolidated report: readiness verdict and the structured report object.
 *
 * docs/10_AUTONOMOUS_PLATFORM.md §9 Phase 5. computeReadiness turns the run's
 * results into a deployment-readiness verdict; buildReport assembles the single
 * document a user reads. Rendering that object to Markdown is the report_render
 * tool; keeping the DATA here means the verdict is computed once and testable
 * without any formatting.
 */
import { buildRecommendations, summariseRecommendations, PRIORITY_LABEL } from './guidance.js';

const isBlockingSeverity = (s) => s === 'critical' || s === 'high';

/**
 * The deployment-readiness verdict.
 *
 * What BLOCKS a deploy is what can be judged reliably: a high or critical
 * security finding, and an endpoint whose tests could not even run (a crash, a
 * 5xx, a refused connection), which means the app is genuinely broken.
 *
 * A failed ASSERTION is a WARNING, not a blocker. The functional tests are
 * generated by a model that guesses the contract, so a mismatch (it expected a
 * 405 where the app returns 404, or an admin route it has no token for) usually
 * means the generated test was wrong, not the app. Hard-blocking a deploy on a
 * model's guess is user-hostile, so those are surfaced prominently and left to
 * the reader's judgement. Ready means no blockers.
 */
export function computeReadiness(assessment) {
  const blockers = [];
  const warnings = [];

  for (const f of assessment.security?.findings ?? []) {
    if (isBlockingSeverity(f.severity)) {
      blockers.push(`${f.severity.toUpperCase()} ${f.category}: ${f.title}`);
    } else if (f.severity === 'medium') {
      warnings.push(`${f.category}: ${f.title}`);
    }
  }

  const tested = (assessment.endpoints ?? []).filter((e) => e.status === 'complete');

  // An endpoint that ERRORED could not complete its request: a crash, a 5xx or a
  // refused connection. That is a real "the app is broken" signal, so it blocks.
  const errored = tested.filter((e) => (e.errored ?? 0) > 0);
  for (const e of errored) {
    blockers.push(`${e.method} ${e.path}: ${e.errored} test(s) could not run (crash or 5xx)`);
  }

  // A failed assertion is a warning: the generated test may have mis-guessed the
  // contract. Surface the total and the endpoints, but do not block on it.
  const withFailures = tested.filter((e) => (e.failed ?? 0) > 0);
  if (withFailures.length) {
    const total = withFailures.reduce((n, e) => n + (e.failed ?? 0), 0);
    warnings.push(
      `${total} generated assertion(s) failed across ${withFailures.length} endpoint(s) `
      + `(${withFailures.map((e) => `${e.method} ${e.path}`).join(', ')}). `
      + 'Generated tests can guess the contract wrong; review before relying on them.',
    );
  }

  // Low-confidence assertions that missed are the generator's own flagged
  // guesses (run_test_case). They are neither blockers nor failures; note the
  // total plainly so a reader knows a guess did not hold, without mistaking it
  // for a defect.
  const softTotal = tested.reduce((n, e) => n + (e.softFailed ?? 0), 0);
  if (softTotal) {
    warnings.push(
      `${softTotal} low-confidence check(s) did not match. The generator flagged these `
      + 'as guesses, so they are not counted as failures; review only if curious.',
    );
  }

  const skipped = (assessment.endpoints ?? []).filter((e) => e.status === 'skipped');
  if (skipped.length && !assessment.baseUrl) {
    warnings.push(`${skipped.length} endpoint(s) not tested: the app was not started.`);
  }
  const unresolved = (assessment.clarifications ?? []).filter((c) => !c.answer);
  if (unresolved.length) warnings.push(`${unresolved.length} open clarification question(s).`);

  return { ready: blockers.length === 0, blockers, warnings };
}

/** Assembles the structured consolidated report. */
export function buildReport(assessment, model) {
  const endpoints = assessment.endpoints ?? [];
  const tested = endpoints.filter((e) => e.status === 'complete');
  const passed = tested.reduce((n, e) => n + (e.passed ?? 0), 0);
  const failed = tested.reduce((n, e) => n + (e.failed ?? 0), 0);
  const findings = assessment.security?.findings ?? [];
  const recommendations = buildRecommendations({ assessment, model });

  return {
    generatedAt: new Date().toISOString(),
    project: {
      framework: model?.framework ?? 'unknown',
      endpointCount: model?.endpointCount ?? endpoints.length,
      dependencyCount: (model?.dependencies ?? []).length,
    },
    discoveredApis: endpoints.map((e) => ({ method: e.method, path: e.path, intent: e.intent, confidence: e.confidence })),
    testing: {
      endpointsTested: tested.length,
      endpointsSkipped: endpoints.filter((e) => e.status === 'skipped').length,
      assertionsPassed: passed,
      assertionsFailed: failed,
      lowConfidenceUnmatched: tested.reduce((n, e) => n + (e.softFailed ?? 0), 0),
      endpointsWithFailures: tested.filter((e) => (e.failed ?? 0) > 0).map((e) => `${e.method} ${e.path}`),
    },
    security: {
      total: findings.length,
      bySeverity: assessment.security?.summary?.bySeverity ?? {},
      findings: findings.map((f) => ({
        severity: f.severity, confidence: f.confidence, category: f.category,
        title: f.title, evidence: f.evidence, remediation: f.remediation,
        location: f.location,
      })),
      notes: assessment.security?.notes ?? [],
    },
    readiness: assessment.readiness ?? { ready: false, blockers: [], warnings: [] },
    clarifications: (assessment.clarifications ?? []).map((c) => ({ endpoint: c.endpoint, question: c.question, answer: c.answer })),
    // The advisory layer: why each issue happened and how to fix it, prioritised.
    recommendations,
    recommendationSummary: summariseRecommendations(recommendations),
  };
}

/** Renders the structured report object to Markdown (report_render uses this). */
export function renderReportMarkdown(report) {
  const L = [];
  const w = (...lines) => L.push(...lines);
  const r = report.readiness ?? {};

  w(`# Assessment report`, '', `Generated ${report.generatedAt}`, '');
  w(`## Readiness: ${r.ready ? 'READY' : 'NOT READY'}`, '');
  if (r.blockers?.length) w('**Blockers:**', ...r.blockers.map((b) => `- ${b}`), '');
  if (r.warnings?.length) w('**Warnings:**', ...r.warnings.map((x) => `- ${x}`), '');

  const recs = report.recommendations ?? [];
  if (recs.length) {
    w('## Recommendations', '', 'What to fix, why it matters, and how, in priority order.', '');
    for (const rec of recs) {
      w(`### [${PRIORITY_LABEL[rec.priority] ?? rec.priority}] ${rec.stage}: ${rec.title}`,
        `- Why: ${rec.why}`,
        `- Fix: ${rec.fix}`,
        ...(rec.where?.length ? [`- Where: ${rec.where.join(', ')}`] : []),
        ...(rec.tips?.length ? ['- Tips:', ...rec.tips.map((tip) => `  - ${tip}`)] : []),
        '');
    }
  }

  w('## Project', '',
    `- Framework: ${report.project.framework}`,
    `- Endpoints discovered: ${report.project.endpointCount}`,
    `- Dependencies: ${report.project.dependencyCount}`, '');

  w('## Discovered APIs', '');
  if (report.discoveredApis.length) {
    w('| Method | Path | Inferred intent |', '| --- | --- | --- |',
      ...report.discoveredApis.map((e) => `| ${e.method} | ${e.path} | ${e.intent ?? ''} |`), '');
  } else {
    w('None discovered.', '');
  }

  const t = report.testing;
  w('## Testing', '',
    `- Endpoints tested: ${t.endpointsTested} (skipped ${t.endpointsSkipped})`,
    `- Assertions passed: ${t.assertionsPassed}, failed: ${t.assertionsFailed}`,
    ...(t.lowConfidenceUnmatched
      ? [`- Low-confidence checks that did not match (guesses, not failures): ${t.lowConfidenceUnmatched}`]
      : []),
    '');
  if (t.endpointsWithFailures.length) w('Endpoints with failures:', ...t.endpointsWithFailures.map((e) => `- ${e}`), '');

  w('## Security', '', `${report.security.total} finding(s).`, '');
  for (const f of report.security.findings) {
    w(`### [${f.severity}] ${f.title}`,
      `- Category: ${f.category} (confidence: ${f.confidence})`,
      f.location?.file ? `- Location: ${f.location.file}${f.location.line ? `:${f.location.line}` : ''}` : (f.location?.endpoint ? `- Endpoint: ${f.location.endpoint}` : ''),
      f.evidence ? `- Evidence: ${f.evidence}` : '',
      f.remediation ? `- Fix: ${f.remediation}` : '', '');
  }
  for (const n of report.security.notes) w(`> ${n}`);
  w('', '_This is not a guarantee of security. Static and dynamic checks cover common issues, not all of them._');

  return L.filter((line) => line !== undefined).join('\n');
}
