/**
 * OpenAPI ingestion.
 *
 * docs/01_PRD.md F4 acceptance criteria:
 *   real specs parse
 *   spec-grounded generation references DECLARED fields
 *   a malformed spec produces a helpful error, not a stack trace
 *
 * Tested against both fixture specs and a real Petstore 3.1 document. The
 * fixture specs are the same files the grounding ablation is measured on, so
 * parsing them here is not a toy exercise.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import request from 'supertest';
import { readFile } from 'node:fs/promises';
import { connectTestDb, disconnectTestDb } from './helpers/mongo.js';
import { registerAllTools } from '../src/mcp/tools/index.js';
import { getTool } from '../src/mcp/registry.js';
import { grantStore, RISK_CLASS } from '../src/mcp/permissions.js';
import { parseDocument, extractOperations } from '../src/mcp/tools/parse_openapi.js';
import {
  importSpecFromText, importSpecFromUrl, authConfigFromSpec, SpecError,
} from '../src/services/spec.service.js';
import { buildPrompt } from '../src/agents/testing.agent.js';
import { ApiSpec } from '../src/models/ApiSpec.js';
import { User } from '../src/models/User.js';
import { createApp } from '../src/app.js';
import { AuditEvent } from '../src/models/AuditEvent.js';

const app = createApp({ logging: false });
let user;
let token;

/** The real fixture spec, generated by fixtures/shared/openapi.js. */
const FIXTURE_SPEC = new URL('../../fixtures/hardened-api/openapi.json', import.meta.url);

/** A genuine OpenAPI 3.1 document with $refs, a path param and bearer auth. */
const PETSTORE_YAML = `openapi: 3.1.0
info:
  title: Swagger Petstore
  version: 1.0.0
servers:
  - url: https://petstore.example.com/v1
components:
  securitySchemes:
    petstoreAuth:
      type: http
      scheme: bearer
    apiKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
  schemas:
    Pet:
      type: object
      required: [id, name]
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        tag: { type: string }
    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: integer }
        message: { type: string }
paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      parameters:
        - name: limit
          in: query
          required: false
          schema: { type: integer, maximum: 100 }
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Pet' }
        'default':
          description: unexpected error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /pets/{petId}:
    get:
      operationId: showPetById
      summary: Info for a specific pet
      security:
        - petstoreAuth: []
      parameters:
        - name: petId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Pet' }
        '404':
          description: Pet not found
`;

function runner() {
  const context = { userId: user._id, sessionId: 'spec' };
  return (name, input, extra = {}) => getTool(name).handler(input, { ...context, ...extra });
}

beforeAll(async () => {
  await connectTestDb();
  await registerAllTools();
});

afterAll(async () => { await disconnectTestDb(); });

beforeEach(async () => {
  await User.deleteMany({});
  await ApiSpec.deleteMany({});
  await AuditEvent.collection.deleteMany({});
  grantStore.clear();
  const res = await request(app).post('/api/auth/register').send({
    displayName: 'Spec', email: 'spec@example.com',
    password: 'correct-horse-battery', confirmPassword: 'correct-horse-battery',
  });
  token = res.body.data.token;
  user = await User.findOne({ email: 'spec@example.com' });
});

// ── Parsing ──────────────────────────────────────────────────────────────────

describe('parseDocument', () => {
  it('parses YAML', () => {
    expect(parseDocument(PETSTORE_YAML).info.title).toBe('Swagger Petstore');
  });

  it('parses JSON', () => {
    expect(parseDocument('{"info":{"title":"J"}}').info.title).toBe('J');
  });

  it('names the LINE for malformed JSON', () => {
    // docs/01_PRD.md F4: "clear parse error naming the offending path, not a
    // stack trace".
    expect(() => parseDocument('{\n "a": 1,\n "b" 2\n}')).toThrow(/line 3/);
  });

  it('names the LINE AND COLUMN for malformed YAML', () => {
    expect(() => parseDocument('a:\n  - x\n bad: indent')).toThrow(/line \d+, column \d+/);
  });

  it('rejects an empty document with a readable message', () => {
    expect(() => parseDocument('   ')).toThrow(/empty/i);
  });
});

describe('extractOperations', () => {
  it('extracts every method on every path', () => {
    const ops = extractOperations(parseDocument(PETSTORE_YAML));
    expect(ops).toHaveLength(2);
    expect(ops.map((o) => `${o.method} ${o.path}`).sort())
      .toEqual(['GET /pets', 'GET /pets/{petId}']);
  });

  it('captures declared parameters with their location and requiredness', () => {
    const ops = extractOperations(parseDocument(PETSTORE_YAML));
    const byId = ops.find((o) => o.operationId === 'showPetById');
    expect(byId.parameters).toEqual([
      { name: 'petId', in: 'path', required: true, schema: { type: 'string' } },
    ]);
  });

  it('captures declared status codes', () => {
    const ops = extractOperations(parseDocument(PETSTORE_YAML));
    const byId = ops.find((o) => o.operationId === 'showPetById');
    expect(byId.responses.map((r) => r.status).sort()).toEqual(['200', '404']);
  });

  it('captures the operation security scheme', () => {
    const ops = extractOperations(parseDocument(PETSTORE_YAML));
    expect(ops.find((o) => o.operationId === 'showPetById').security).toEqual(['petstoreAuth']);
  });
});

// ── Import ───────────────────────────────────────────────────────────────────

describe('importSpecFromText', () => {
  it('imports the Petstore 3.1 spec and persists its operations', async () => {
    const { spec } = await importSpecFromText({
      userId: user._id, text: PETSTORE_YAML, runTool: runner(),
    });
    expect(spec.title).toBe('Swagger Petstore');
    expect(spec.openapi).toBe('3.1.0');
    expect(spec.operationCount).toBe(2);
    expect(await ApiSpec.countDocuments({ userId: user._id })).toBe(1);
  });

  it('dereferences $refs so grounding sees real schemas', async () => {
    const { spec } = await importSpecFromText({
      userId: user._id, text: PETSTORE_YAML, runTool: runner(),
    });
    // If $ref survived, this would still contain the pointer string.
    expect(JSON.stringify(spec.operations)).not.toContain('$ref');
  });

  it('imports BOTH fixture specs, the grounding-ablation targets', async () => {
    const text = await readFile(FIXTURE_SPEC, 'utf8');
    const { spec } = await importSpecFromText({
      userId: user._id, text, runTool: runner(),
    });
    expect(spec.operationCount).toBe(8);
    expect(spec.securitySchemes.map((s) => s.name)).toContain('bearerAuth');
  });

  it('records the parse as an audited tool call', async () => {
    await importSpecFromText({ userId: user._id, text: PETSTORE_YAML, runTool: runner() });
    const rows = await AuditEvent.find({ tool: 'parse_openapi' }).lean();
    expect(rows).toHaveLength(1);
    expect(rows[0].outcome).toBe('ok');
    expect(rows[0].riskClass).toBe('local.compute');
  });

  it('rejects a document with no operations rather than storing an empty spec', async () => {
    // A path entry carrying no HTTP method: structurally valid OpenAPI, but
    // there is nothing to generate tests against. (`paths: {}` is rejected
    // earlier by swagger-parser's own validation, which is also correct: this
    // covers the case that reaches OUR check.)
    const err = await importSpecFromText({
      userId: user._id,
      text: 'openapi: 3.1.0\ninfo:\n  title: Empty\n  version: "1"\npaths:\n  /thing: {}',
      runTool: runner(),
    }).catch((e) => e);

    expect(err.code).toBe('SPEC_NO_OPERATIONS');
    expect(err.message).toMatch(/declares no operations/i);
    expect(await ApiSpec.countDocuments({ userId: user._id })).toBe(0);
  });

  it('surfaces a located parse error, not a stack trace', async () => {
    const err = await importSpecFromText({
      userId: user._id, text: '{\n"openapi": "3.1.0"\n"bad": true\n}', runTool: runner(),
    }).catch((e) => e);
    expect(err).toBeInstanceOf(SpecError);
    expect(err.code).toBe('SPEC_PARSE_ERROR');
    expect(err.message).toMatch(/line \d+/);
    expect(err.message).not.toMatch(/at Object\.|node:internal/); // no stack
  });
});

describe('importSpecFromUrl: the SSRF surface', () => {
  it('REFUSES a spec URL pointing at the cloud metadata endpoint', async () => {
    // "Import this spec from 169.254.169.254" is a credential-theft attempt in
    // a helpful costume. The fetch goes through http_request, so the egress
    // guard applies.
    grantStore.grant({
      userId: user._id, sessionId: 'spec',
      riskClass: RISK_CLASS.NETWORK_READ, host: '169.254.169.254',
    });
    const err = await importSpecFromUrl({
      userId: user._id, url: 'http://169.254.169.254/latest/meta-data/', runTool: runner(),
      context: { userId: user._id, sessionId: 'spec' },
    }).catch((e) => e);

    expect(err.code).toBe('SPEC_URL_BLOCKED');
    const rows = await AuditEvent.find({ tool: 'http_request' }).lean();
    expect(rows[0].outcome).toBe('blocked_ssrf');
  });

  it('refuses an ungranted host before fetching', async () => {
    const err = await importSpecFromUrl({
      userId: user._id, url: 'https://example.com/openapi.json', runTool: runner(),
      context: { userId: user._id, sessionId: 'spec' },
    }).catch((e) => e);
    expect(err.code).toBe('SPEC_FETCH_FAILED');
  });
});

// ── Grounding ────────────────────────────────────────────────────────────────

describe('spec-grounded prompt construction', () => {
  it('references DECLARED parameters, status codes and security schemes', async () => {
    const ops = extractOperations(parseDocument(PETSTORE_YAML));
    const operation = ops.find((o) => o.operationId === 'showPetById');

    const grounded = buildPrompt({
      url: 'https://petstore.example.com/v1', method: 'GET',
      description: 'fetch a pet', operation,
    });

    expect(grounded).toContain('/pets/{petId}');
    expect(grounded).toContain('petId (path, required)');
    expect(grounded).toContain('404');
    expect(grounded).toContain('petstoreAuth');
    expect(grounded).toMatch(/declared status codes/i);
  });

  it('an ungrounded prompt mentions no specification at all', () => {
    const plain = buildPrompt({
      url: 'https://petstore.example.com/v1', method: 'GET', description: 'fetch a pet',
    });
    expect(plain).not.toMatch(/OpenAPI/i);
    expect(plain).not.toContain('petId');
  });
});

describe('authConfigFromSpec', () => {
  it('turns a bearer scheme into the header the run form should ask for', async () => {
    const { spec } = await importSpecFromText({
      userId: user._id, text: PETSTORE_YAML, runTool: runner(),
    });
    const operation = spec.operations.find((o) => o.operationId === 'showPetById');
    expect(authConfigFromSpec(spec, operation)).toEqual([
      { scheme: 'petstoreAuth', header: 'Authorization', prefix: 'Bearer ', valueRequired: true },
    ]);
  });

  it('handles an apiKey scheme', async () => {
    const { spec } = await importSpecFromText({
      userId: user._id, text: PETSTORE_YAML, runTool: runner(),
    });
    const config = authConfigFromSpec(spec, { security: ['apiKeyAuth'] });
    expect(config[0]).toMatchObject({ scheme: 'apiKeyAuth', prefix: '' });
  });

  it('never invents a credential value', async () => {
    const { spec } = await importSpecFromText({
      userId: user._id, text: PETSTORE_YAML, runTool: runner(),
    });
    const config = authConfigFromSpec(spec, spec.operations[1]);
    for (const c of config) expect(c).not.toHaveProperty('value');
  });
});

// ── HTTP surface ─────────────────────────────────────────────────────────────

describe('POST /api/specs/import', () => {
  it('requires authentication', async () => {
    expect((await request(app).post('/api/specs/import').send({ spec: PETSTORE_YAML })).status).toBe(401);
  });

  it('imports pasted YAML and returns the operation list', async () => {
    const res = await request(app).post('/api/specs/import')
      .set('Authorization', `Bearer ${token}`)
      .send({ spec: PETSTORE_YAML, filename: 'petstore.yaml' });
    expect(res.status).toBe(201);
    expect(res.body.data.spec.operationCount).toBe(2);
    expect(res.body.data.spec.operations[0]).toHaveProperty('path');
  });

  it('returns 400 with a located message for a malformed document', async () => {
    const res = await request(app).post('/api/specs/import')
      .set('Authorization', `Bearer ${token}`)
      .send({ spec: '{\n"a": 1,\n"b" 2\n}' });
    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe('SPEC_PARSE_ERROR');
    expect(res.body.error.message).toMatch(/line \d+/);
  });

  it('warns about a very large operation count rather than refusing', async () => {
    const paths = {};
    for (let i = 0; i < 501; i += 1) {
      paths[`/r${i}`] = { get: { responses: { 200: { description: 'ok' } } } };
    }
    const res = await request(app).post('/api/specs/import')
      .set('Authorization', `Bearer ${token}`)
      .send({ spec: JSON.stringify({ openapi: '3.1.0', info: { title: 'Big', version: '1' }, paths }) });
    expect(res.status).toBe(201);
    expect(res.body.data.warnings.join(' ')).toMatch(/501 operations/);
  });
});

describe('GET /api/specs/:id: same IDOR discipline as runs', () => {
  it('returns 404 for another user spec', async () => {
    const other = await User.create({
      email: 'other@example.com', displayName: 'Other',
      authProviders: [{ provider: 'local', providerId: 'other@example.com', email: 'other@example.com' }],
    });
    const theirs = await ApiSpec.create({
      userId: other._id, title: 'Private API', operations: [], operationCount: 0,
    });
    const res = await request(app).get(`/api/specs/${theirs._id}`)
      .set('Authorization', `Bearer ${token}`);
    expect(res.status).toBe(404);
    expect(JSON.stringify(res.body)).not.toContain('Private API');
  });

  it('lists only this user specs', async () => {
    await importSpecFromText({ userId: user._id, text: PETSTORE_YAML, runTool: runner() });
    const res = await request(app).get('/api/specs').set('Authorization', `Bearer ${token}`);
    expect(res.body.data.specs).toHaveLength(1);
  });
});
